services:
  localstack:
    image: ${LOCALSTACK_DOCKER_IMAGE:-localstack/localstack:4@sha256:8a2a5b507ae0aae700e4f3ef8527cbbe8af8f14a19a003bd64ed8291a347e33c}
    environment:
      SERVICES: dynamodb,sts,ssm,secretsmanager,s3,logs
      PERSISTENCE: "1"
      LOCALSTACK_AUTH_TOKEN: ${LOCALSTACK_AUTH_TOKEN:-}
    ports:
      - "4566:4566"
    volumes:
      - localstack-data:/var/lib/localstack

volumes:
  localstack-data:
