from __future__ import annotations

from datetime import datetime
from typing import Protocol

from campfire_api.contexts.identity.domain.entities import (
    Credentials,
    PreferencesProfile,
    RefreshToken,
    Session,
    User,
)
from campfire_api.contexts.identity.domain.value_objects import Email, UserId


class UserRepository(Protocol):
    async def get_by_email(self, email: Email) -> User | None: ...
    async def get_by_id(self, user_id: UserId) -> User | None: ...
    async def add(self, user: User) -> None: ...
    async def update(self, user: User) -> None: ...


class CredentialsRepository(Protocol):
    async def get_by_user_id(self, user_id: UserId) -> Credentials | None: ...
    async def add(self, credentials: Credentials) -> None: ...


class PreferencesRepository(Protocol):
    async def get_by_user_id(self, user_id: UserId) -> PreferencesProfile | None: ...
    async def add(self, preferences: PreferencesProfile) -> None: ...
    async def replace(self, preferences: PreferencesProfile) -> None: ...


class SessionRepository(Protocol):
    async def add(self, session: Session) -> None: ...
    async def get_by_access_fingerprint(self, fingerprint: bytes) -> Session | None: ...
    async def revoke(self, session_id: object, reason: str, now: datetime) -> None: ...
    async def revoke_family(self, family_id: object, reason: str, now: datetime) -> None: ...


class RefreshTokenRepository(Protocol):
    async def add(self, token: RefreshToken) -> None: ...
    async def get_by_fingerprint(self, fingerprint: bytes) -> RefreshToken | None: ...
    async def consume_atomic(self, token_id: object, now: datetime) -> RefreshToken | None: ...
    async def revoke_family(self, family_id: object, reason: str, now: datetime) -> None: ...


class PasswordHasher(Protocol):
    async def hash(self, plaintext: str) -> str: ...
    async def verify(self, plaintext: str, password_hash: str) -> bool: ...


class TokenIssuer(Protocol):
    async def issue_access_token(self) -> tuple[str, bytes, datetime]: ...
    async def issue_refresh_token(self) -> tuple[str, bytes, datetime]: ...
    def fingerprint(self, token: str) -> bytes: ...


class Clock(Protocol):
    def now(self) -> datetime: ...


class RateLimiter(Protocol):
    async def check(self, client_ip: str, target_email: str) -> None: ...
